# Generated by Django 5.2.10 on 2026-01-31 00:00

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_uz",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="post",
            name="content_uz",
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt_uz",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description_uz",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_title_uz",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="post",
            name="title_uz",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
