# Generated by Django 5.2.10 on 2026-01-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_profile_full_name_profile_skills_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
