# Generated by Django 5.2.10 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("me", "0003_profile_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
