# Generated by Django 5.2.10 on 2026-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("me", "0004_contactmessage_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio_uz",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="role_uz",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="profile",
            name="tagline_uz",
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
