# Generated by Django 5.2.10 on 2026-01-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_assistantlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantlog',
            name='model_used',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='assistantlog',
            name='status',
            field=models.CharField(default='ok', max_length=20),
        ),
        migrations.AddField(
            model_name='assistantlog',
            name='tokens_used',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
