# Generated by Django 5.2.10 on 2026-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_assistantlog_model_used_assistantlog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantlog',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistantlog',
            name='provider',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
