# Generated by Django 5.2.10 on 2026-01-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcategory",
            name="name_uz",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="project",
            name="description_uz",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="meta_description_uz",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="meta_title_uz",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack_uz",
            field=models.TextField(blank=True, help_text="Comma-separated tech stack"),
        ),
        migrations.AddField(
            model_name="project",
            name="title_uz",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
